
[@摄魂雷1]
#IF
EQUAL U20 0
not checkgold 50000
#ACT
材料不够！
break

#IF
EQUAL U20 0
checkgold 500000
#ACT
MOV U20 2
take 金币 500000
goto @魂环临时
break


#IF
EQUAL U20 1
#ACT
MOV U20 2
goto @魂环临时
break
#IF
EQUAL U20 2
#ACT
MOV U20 1
goto @魂环临时
break