;                      不要的变量请在此列填写处增加“;”符号

#DEFINE $常量_母端位置 D:\屠魔传仙\Mirserver母\


#DEFINE $常量_网关标识 cxj3
#DEFINE $常量_网关编号 9
#DEFINE $常量_微信NC T493
#DEFINE $常量_微信OP T491
#DEFINE $常量_机器码 T492

#DEFINE $常量_角色ID U496

#DEFINE $常量_验证地图 微信验证		//微信验证地图
#DEFINE $常量_主城地图号 礼包房间
#DEFINE $常量_主城地图X 23
#DEFINE $常量_主城地图Y 25

#DEFINE $常量_游戏名称 传仙记[第三季]	        //游戏版本号名称

#DEFINE $常量_补丁编号 76		//补丁编号
#DEFINE $常量_按钮编号 0		//按钮_ADDBUTTON的编号 需要修改脚本QFunction.txt [@ButtonClickxxx]


#DEFINE $常量_转区标示 998	//转区后封号标示 Check [116] 1

#DEFINE $常量_点击间隔 1200 	//NPC点击间隔_毫秒 1000=1秒
#DEFINE $常量_本区充值金额 U499		//本区平台真实充值
#DEFINE $常量_JZ转区已领取 U498		//本区已经领取转区点 